name       : libchewing
version    : 0.5.1
release    : 2
source     :
    - https://github.com/chewing/libchewing/releases/download/v0.5.1/libchewing-0.5.1.tar.bz2 : 9708c63415fa6034435c0f38100e7d30d0e1bac927f67bec6dfeb3fef016172b
license    : LGPL-2.1-only
component  : desktop.library
summary    : Chewing is an intelligent phonetic (Zhuyin/Bopomofo) input method
description: |
    Chewing is an intelligent phonetic (Zhuyin/Bopomofo) input method
builddeps  :
    - pkgconfig(sqlite3)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/libchewing.a